It seems to be an known issue of mpi4py. From https://groups.google.com/forum/#!topic/mpi4py/RovYzJ8qkbc, I read:

>mpi4py initializes/finalizes MPI for you. The initialization occurs at
import time, and the finalization when the Python process is about to
finalize (I'm using Py_AtExit() C-API call to do this). As
MPI_Finalize() is collective and likely blocking in most MPI impls,
you get the deadlock.

A solution is to override  `sys.excepthook`and call explicitly `MPI.COMM_WORLD.Abort` in it.

Here is your code modified:

    import sys
    import time
    import mpi4py.MPI
    mpi_comm = mpi4py.MPI.COMM_WORLD
    
    def mpiabort_excepthook(type, value, traceback):
        mpi_comm.Abort()
        sys.__excepthook__(type, value, traceback)
    
    def main():
        if mpi_comm.rank == 0:
            raise ValueError('Failure')
    
    
        print('{} continuing to execute'.format(mpi_comm.rank))
        time.sleep(10)
        print('{} exiting'.format(mpi_comm.rank))
    
    if __name__ == "__main__":
        sys.excepthook = mpiabort_excepthook
        main()
        sys.excepthook = sys.__excepthook__

