<p>It seems to be an known issue of mpi4py. From <a href="https://groups.google.com/forum/#!topic/mpi4py/RovYzJ8qkbc" rel="nofollow noreferrer">https://groups.google.com/forum/#!topic/mpi4py/RovYzJ8qkbc</a>, I read:</p>
<blockquote>
<p>mpi4py initializes/finalizes MPI for you. The initialization occurs at
import time, and the finalization when the Python process is about to
finalize (I'm using Py_AtExit() C-API call to do this). As
MPI_Finalize() is collective and likely blocking in most MPI impls,
you get the deadlock.</p>
</blockquote>
<p>A solution is to override  <code>sys.excepthook</code>and call explicitly <code>MPI.COMM_WORLD.Abort</code> in it.</p>
<p>Here is your code modified:</p>
<pre><code>import sys
import time
import mpi4py.MPI
mpi_comm = mpi4py.MPI.COMM_WORLD

def mpiabort_excepthook(type, value, traceback):
    mpi_comm.Abort()
    sys.__excepthook__(type, value, traceback)

def main():
    if mpi_comm.rank == 0:
        raise ValueError('Failure')


    print('{} continuing to execute'.format(mpi_comm.rank))
    time.sleep(10)
    print('{} exiting'.format(mpi_comm.rank))

if __name__ == &quot;__main__&quot;:
    sys.excepthook = mpiabort_excepthook
    main()
    sys.excepthook = sys.__excepthook__
</code></pre>
